# Learn Numpy

## 参考资料

- [Bilibili | 一个10分钟的numpy入门教程](https://www.bilibili.com/video/BV1Wy4y1h7ii/?spm_id_from=333.880.my_history.page.click&vd_source=0827bcf789df7e0812ec44f70f9a82ec)
- [官方文档 | NumPy: the absolute basics for beginners](https://numpy.org/doc/stable/user/absolute_beginners.html)
- [开源电子书 | 从python到numpy](https://www.labri.fr/perso/nrougier/from-python-to-numpy/)

### 1. 导入`numpy`

In [4]:
import numpy as np

### 2. 从python原生array转换到`numpy`的array

In [5]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [6]:
# 获取数组的尺寸
a.shape

(5,)

In [7]:
a= np.zeros((3, 2))
print(a)
print(a.shape)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
(3, 2)


In [8]:
np.ones((2, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
# 递增或递减的数列
np.arange(3, 7)

array([3, 4, 5, 6])

In [10]:
# 区间等间距分布的数
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [11]:
# 生成随机的数组
np.random.rand(2, 4)

array([[0.23001298, 0.78655462, 0.42134038, 0.64597029],
       [0.07744212, 0.32823275, 0.53963136, 0.31745753]])

### 3. 默认的数据类型为浮点数

In [12]:
a = np.zeros((2, 4))
a.dtype

dtype('float64')

In [13]:
# 显式指定数据类型
a = np.zeros((4, 2), dtype = np.int32)
a

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

---
### 增加、删除元素，排序
涉及   
- `np.osrt()`
- `np.concatenate()`

In [15]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [17]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
x = np.array([[1, 2],
              [3, 4]
              ])
y = np.array([
    [5, 6]
    ])
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

---
### 数组大小
涉及    
- `ndarray.ndim`
- `ndarray.size`
- `ndarray.shape`

In [19]:
array_example = np.array([
  [
      [0, 1, 2, 3],
      [4, 5, 6, 7]
  ],
  [
      [0, 1, 2, 3],
      [4, 5, 6, 7]
  ],
  [
      [0, 1, 2, 3],
      [4, 5, 6, 7]
  ]
])
array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [20]:
# 数组的维度
array_example.ndim

3

In [21]:
# 数组元素总数
array_example.size

24

In [22]:
# 数据的各维度大小(shape)
array_example.shape

(3, 2, 4)

---
### 重塑(reshape)数组
涉及
- `arr.reshape()`

In [23]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [26]:
# 重塑成3行2列的数组
b = a.reshape(3, 2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

---
### 从`一维数组`转为`二维数组`
涉及    
- `np.newaxis`
- `np.expand_dims`