# Learn Numpy

## 参考资料

- [Bilibili | 一个10分钟的numpy入门教程](https://www.bilibili.com/video/BV1Wy4y1h7ii/?spm_id_from=333.880.my_history.page.click&vd_source=0827bcf789df7e0812ec44f70f9a82ec)
- [开源电子书 | 从python到numpy](https://www.labri.fr/perso/nrougier/from-python-to-numpy/)

### 1. 导入`numpy`

In [1]:
import numpy as np

### 2. 从python原生array转换到`numpy`的array

In [8]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [11]:
# 获取数组的尺寸
a.shape

(5,)

In [14]:
a= np.zeros((3, 2))
print(a)
print(a.shape)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
(3, 2)


In [6]:
np.ones((2, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
# 递增或递减的数列
np.arange(3, 7)

array([3, 4, 5, 6])

In [17]:
# 区间等间距分布的数
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])