In [2]:
import numpy as np

In [3]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [4]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [4]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [6]:
np.arange(3, 7)

array([3, 4, 5, 6])