# Learn Numpy

## 参考资料

- [Bilibili | 一个10分钟的numpy入门教程](https://www.bilibili.com/video/BV1Wy4y1h7ii/?spm_id_from=333.880.my_history.page.click&vd_source=0827bcf789df7e0812ec44f70f9a82ec)
- [官方文档 | NumPy: the absolute basics for beginners](https://numpy.org/doc/stable/user/absolute_beginners.html)
- [开源电子书 | 从python到numpy](https://www.labri.fr/perso/nrougier/from-python-to-numpy/)

### 1. 导入`numpy`

In [2]:
import numpy as np

### 2. 从python原生array转换到`numpy`的array

In [3]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [4]:
# 获取数组的尺寸
a.shape

(5,)

In [5]:
a= np.zeros((3, 2))
print(a)
print(a.shape)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
(3, 2)


In [6]:
np.ones((2, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
# 递增或递减的数列
np.arange(3, 7)

array([3, 4, 5, 6])

In [8]:
# 区间等间距分布的数
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [9]:
# 生成随机的数组
np.random.rand(2, 4)

array([[0.40316523, 0.24361434, 0.30369784, 0.78792784],
       [0.05655426, 0.83852102, 0.82709771, 0.03240927]])

### 3. 默认的数据类型为浮点数

In [13]:
a = np.zeros((2, 4))
a.dtype

dtype('float64')

In [15]:
# 显式指定数据类型
a = np.zeros((4, 2), dtype = np.int32)
a

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])