# For Beginners


In [2]:
import numpy as np

### 从`List`转换为numpy `array`

In [4]:
# 一维数组
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [6]:
# 多维数组
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### 使用索引访问数组元素

In [7]:
a[0]

array([1, 2, 3, 4])

- Vector: 一维数组
- Matrix: 二位数组
- tensor: 多维数组

`维度`(dimensions)被称为`轴`(axes)

---
### 创建基本数组

涉及    
- `np.array()` 
- `np.zeros()`
- `np.ones()`
- `np.empty()`
- `np.arange()`
- `np.linspace()`
- `dtype`

In [9]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [10]:
np.zeros(2)

array([0., 0.])

In [13]:
np.ones((4, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
# empty方法创建初始内容为随机数的数组
np.empty((4, 2))

array([[0.00e+000, 0.00e+000],
       [0.00e+000, 0.00e+000],
       [0.00e+000, 7.65e-321],
       [0.00e+000, 0.00e+000]])

In [15]:
np.arange(4)

array([0, 1, 2, 3])

In [16]:
# 参数分别为第一个数、最后一个数、步数
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [17]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [18]:
# numpy默认的数据类型是浮点Float64，可以显式指定类型
x = np.ones((4, 3), dtype=np.int64)
x

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int64)