# For Beginners

## 参考资料

- [官方文档 | NumPy: the absolute basics for beginners](https://numpy.org/doc/stable/user/absolute_beginners.html)

- [开源电子书 | 从python到numpy](https://www.labri.fr/perso/nrougier/from-python-to-numpy/)

In [2]:
import numpy as np

### 从`List`转换为numpy `array`

In [3]:
# 一维数组
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [4]:
# 多维数组
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### 使用索引访问数组元素

In [5]:
a[0]

array([1, 2, 3, 4])

- Vector: 一维数组
- Matrix: 二位数组
- tensor: 多维数组

`维度`(dimensions)被称为`轴`(axes)

---
### 创建基本数组

涉及    
- `np.array()` 
- `np.zeros()`
- `np.ones()`
- `np.empty()`
- `np.arange()`
- `np.linspace()`
- `dtype`

In [6]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [7]:
np.zeros(2)

array([0., 0.])

In [8]:
np.ones((4, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
# empty方法创建初始内容为随机数的数组
np.empty((4, 2))

array([[0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 4.58492919e-321],
       [1.78019082e-306, 0.00000000e+000]])

In [10]:
np.arange(4)

array([0, 1, 2, 3])

In [11]:
# 参数分别为第一个数、最后一个数、步数
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [12]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [13]:
# numpy默认的数据类型是浮点Float64，可以显式指定类型
x = np.ones((4, 3), dtype=np.int64)
x

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int64)

---
### 增加、删除元素，排序
涉及   
- `np.osrt()`
- `np.concatenate()`

In [14]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
x = np.array([[1, 2],
              [3, 4]
              ])
y = np.array([
    [5, 6]
    ])
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

---
### 数组大小
涉及    
- `ndarray.ndim`
- `ndarray.size`
- `ndarray.shape`

In [17]:
array_example = np.array([
  [
      [0, 1, 2, 3],
      [4, 5, 6, 7]
  ],
  [
      [0, 1, 2, 3],
      [4, 5, 6, 7]
  ],
  [
      [0, 1, 2, 3],
      [4, 5, 6, 7]
  ]
])
array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [18]:
# 数组的维度
array_example.ndim

3

In [19]:
# 数组元素总数
array_example.size

24

In [20]:
# 数据的各维度大小(shape)
array_example.shape

(3, 2, 4)

---
### 重塑(reshape)数组
涉及
- `arr.reshape()`

In [21]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [22]:
# 重塑成3行2列的数组
b = a.reshape(3, 2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

---
### 从`一维数组`转为`二维数组`
涉及    
- `np.newaxis`
- `np.expand_dims`